const { startDevServer } = require('./lib/servers/dev')
const { startRefreshDevServer } = require('./lib/servers/refresh')
const { copyAssets } = require('./lib/assets')
const { compileHtml } = require('./lib/html')
const { compileTypescript } = require('./lib/typescript')
const { consoleSection } = require('./lib/util/console')
const { printNetworkInterfaces } = require('./lib/util/network')

consoleSection('ASSETS', copyAssets)
consoleSection('HTML', compileHtml.bind(null, true))
consoleSection('TYPESCRIPT', compileTypescript.bind(null, true))
consoleSection('REFRESH SERVER', startRefreshDevServer)
consoleSection('APP SERVERS', startDevServer)
consoleSection('NETWORK INTERFACES', printNetworkInterfaces)
consoleSection('OUTPUT')
