#!/usr/bin/env bun

import { Glob } from 'bun';
import { resolve } from 'node:path';
import { extractFrontMatter, stripFrontMatter } from 'scripts/helpers';

const projectRoot = resolve(import.meta.dir, '..');
const specDir = resolve(projectRoot, 'specs');
const wwwDir = resolve(projectRoot, 'www');

// delete the specs directory if it exists, then recreate it with the necessary subdirectories
if (await Bun.file(specDir).exists()) {
  await Bun.file(specDir).unlink();
}

// copy core files to specs/references/core
const coreFiles = [];
for await (const fileName of new Glob('src/core/*.md').scan('.')) {
  const filePath = resolve(projectRoot, fileName);
  const content = await Bun.file(filePath).text();
  const frontMatter = extractFrontMatter(content);
  // copy to references/core
  const referencePath = `${specDir}/references/core/${fileName.split('/').pop()!}`;
  await Bun.write(referencePath, content);
  coreFiles.push([`../references/core/${fileName.split('/').pop()!}`, frontMatter, content]);
}

const traitFiles = [];
for await (const file of new Glob('src/traits/*.md').scan('.')) {
  const filePath = resolve(projectRoot, file);
  const content = await Bun.file(file).text();
  const fileName = file.split('/').pop()!;
  const frontMatter = extractFrontMatter(await Bun.file(filePath).text());
  // copy to references/traits
  const referencePath = `${specDir}/references/traits/${fileName}`;
  await Bun.write(referencePath, content);
  traitFiles.push([`../references/traits/${fileName}`, frontMatter, content]);
}

const stateFiles = [];
for await (const file of new Glob('src/states/*.md').scan('.')) {
  const filePath = resolve(projectRoot, file);
  const content = await Bun.file(file).text();
  const fileName = file.split('/').pop()!;
  const frontMatter = extractFrontMatter(await Bun.file(filePath).text());
  // copy to references/states
  const referencePath = `${specDir}/references/states/${fileName}`;
  await Bun.write(referencePath, content);
  stateFiles.push([`../references/states/${fileName}`, frontMatter, content]);
}

const themeFiles = [];
for await (const file of new Glob('src/themes/tokens/*.md').scan('.')) {
  const filePath = resolve(projectRoot, file);
  const content = await Bun.file(file).text();
  const fileName = file.split('/').pop()!;
  const frontMatter = extractFrontMatter(await Bun.file(filePath).text());
  // copy to references/tokens
  const referencePath = `${specDir}/references/tokens/${fileName}`;
  await Bun.write(referencePath, content);
  themeFiles.push([`../references/tokens/${fileName}`, frontMatter, content]);
}

// Create an empty Skill.md (overwrite if exists)
await Bun.write(
  `${specDir}/agents/oem.md`,
  `---
name: oem
description: Manual for generating front-end applications using OEM, the agent-first UI framework and toolkit.
---

# This Guide

You are a front-end expert and an expert at writing idiomatic OEM. This document is a guide and canonical reference on how OEM applications are structured and how to use the framework effectively and write OEM's distinctive compositional syntax that declaratively unifies markup, styling, and behavior.

## Core Library & Fundamentals

The core library provides the fundamental building blocks of the OEM ecosystem. It includes the Template function for creating a user-defined templating engine, the State function for creating a micro event-bus and state object, and the useThemeState function for managing design tokens in a centralized way. The core library also includes type definitions for OEM, which can be found in the references.

${coreFiles
  .map(
    ([filePath, frontMatter]: any) =>
      `- [${frontMatter.name}](${filePath}) - ${frontMatter.description}`,
  )
  .join('\n')}


## Trait Library

The following traits come with OEM. Traits are reusable pieces of logic that give the abilities and behaviors to your custom template engine. They can be thought of as plugins that can be applied to the output of the Template function to create a powerful and flexible system for generating UI.

${traitFiles
  .map(
    ([filePath, frontMatter]: any) =>
      `- [${frontMatter.name}](${filePath}) - ${frontMatter.description}`,
  )
  .join('\n')}


## State Library

OEM's state management system is simple yet powerful, providing a flexible way to manage state in your applications. The following states are available in the OEM ecosystem:

${stateFiles
  .map(
    ([filePath, frontMatter]: any) =>
      `- [${frontMatter.name}](${filePath}) - ${frontMatter.description}`,
  )
  .join('\n')}

## Theme Library

OEM doesn't have components or other predefined UI elements. Instead, all elements, component, features, etc. are generated by LLMs interpreting design tokens which follows a naming convention that prescribes both structure and usage. This allows for a much more flexible and adaptable system that can be used to generate any kind of UI. 

### Naming:
Semantics > Components

### Tokens:
${themeFiles
  .map(
    ([filePath, frontMatter]: any) =>
      `- [${frontMatter.name}](${filePath}) - ${frontMatter.description}`,
  )
  .join('\n')}

### Creating a useThemeState Instance

For SPAs and any non-trivial app, create a dedicated useThemeState instance in a \`theme.ts\` file:

\`\`\`ts
import { useThemeState } from 'oem/states/ThemeState';
import { darkTheme } from 'oem/themes';
import type { Theme } from 'oem/states/ThemeState';

// Use the built-in dark theme, or define custom tokens
const myDarkTheme: Theme = { name: 'dark', tokens: darkTheme };

export const theme = useThemeState([myDarkTheme]);
\`\`\`

### Using Tokens in the UI

Once you have a useThemeState instance, access tokens via its proxy getters. Every token key on the useThemeState becomes a getter function:

\`\`\`ts
import { theme } from './theme';
import { tag, trait } from './templates';

// Deferred getter (prefixed with $): for reactive traits that need to re-evaluate on theme change
trait.style('backgroundColor', theme.$sem_color_bkg_pri)
\`\`\`

### Deferred Token Getters vs. State Watchers

These are two distinct concepts that must not be confused:

**Token deferred getters** (\`theme.$tokenName\`) are functions passed as the **value** argument to a trait. The trait calls the function to get the current token value, and re-evaluates it when the theme changes:

\`\`\`ts
// theme.$sem_color_bkg_pri is the VALUE — a function the trait calls
trait.style('backgroundColor', theme.$sem_color_bkg_pri)
\`\`\`

**State watchers** are State objects passed in the \`...rest\` position of reactive traits (\`trait.text\`, \`trait.html\`, \`trait.inputValue\`, \`trait.style\` with a condition). The trait subscribes to the State and re-runs whenever it changes:

\`\`\`ts
// machine is the WATCHER — a State object the trait subscribes to
trait.text(() => \`\${machine.val().count} items\`, machine)
trait.html(() => ItemList(), machine)
trait.inputValue(() => machine.val().inputText, machine)
\`\`\`

**The rule:** Watcher arguments are always plain State objects — \`machine\`, \`theme\`, \`myState\`. **Never** pass \`machine.$val\`, \`machine.$test(...)\`, or any other \`$\`-prefixed deferred operation as a watcher. Those are deferred value closures, not State objects.

### Token Usage Rules

- **Never** write a hex value, rgb value, or pixel literal directly in a \`trait.style()\` call
- UI code should reference component (cmp_) or semantic (sem_) tokens only
- **Never invent token keys that don't exist in \`DesignTokens\`.** The cascade \`cmp_ → sem_\` means: check if an existing component token covers this context first, then fall back to semantic. When no \`cmp_\` or \`sem_\` token covers the need, use an inline style as the absolute last resort.


## Pattern Library

### Idiomatic OEM

- Don't use ternary operators. Instead, use traits to conditionally apply styles and behaviors. This keeps the declarative syntax consistent and allows for better LLM interpretation and management.
- **Never hardcode color, spacing, typography, or other design values.** Always derive them from the useThemeState design token system. Follow the token selection cascade (\`cmp_ → sem_\`) and use the first existing token that fits. Only use an inline style when no token in the system covers the need. No hex codes, rgb values, or pixel literals should appear directly in \`trait.style()\` calls.
- Every SPA should instantiate its own useThemeState with a token set appropriate to the app's design, then reference those tokens throughout the UI.
- Theming is handled entirely through design tokens and the useThemeState system. Don't write conditional logic in your templates to handle different themes; instead, use traits that reference tokens which can change based on the active theme. This allows for dynamic theming without coupling your UI logic to specific theme conditions.

### Git Commits

### Architectural Patterns

OEM is designed to be flexible and adaptable to a wide range of architectural patterns. However, there are a few patterns that are particularly well-suited to the OEM ecosystem:

#### SPA

SPAs have a prescribed structure in order to keep a clean separation of concerns. File structure should be based on High Cohesion and Low Coupling and optimized for LLM interpretation and management. Based on complexity, the following items could exist either as single files or folders with files.

- **actions**:
A library of all the actions that can be dispatched in the app. Each action is a function that returns an object with a type and a payload.

- **machines**:
State machines that define the behavior of the app. Each machine has a state, a set of transitions, and a set of actions that can be dispatched. Implement them as simple switch statements, switching on the current state and the dispatched action.

- **main**:
The entry point of the app. It initializes the state machine and sets up the event listeners for the UI. It also renders the UI based on the current state of the machine.

- **templates**:
A library of templates (using Template and it's destructured [tag, trait]) that can be used to render the UI. Multiple templates can be used in the app, but it's often best to keep them organized in a single file or folder.

- **theme**:
A useThemeState instance that defines the app's design tokens in two layers: semantic (sem_) for purpose-based values and component (cmp_) for all UI parts. This is the single source of truth for all visual values (colors, spacing, typography, radii, shadows, etc.). Import and reference these tokens in templates and UI instead of hardcoding values. Create a useThemeState instance by importing \`useThemeState\` from the core library and populating it with at least one Theme (\`{ name: string, tokens: DesignTokens }\`). Use the built-in \`darkTheme\` and/or \`lightTheme\` token sets as a starting point, or define your own. Access tokens in the UI via the useThemeState proxy getters (e.g., \`theme.sem_color_bkg_pri()\` or the deferred form \`theme.$sem_color_bkg_pri\` for use in traits). Token selection cascade: \`cmp_ → sem_ → inline style\`.

- **traits**:
The default traits provided by the core library are often sufficient for most use cases, but you may find that you need to create custom traits to handle specific behaviors or patterns in your app. This file or folder can be used to store any custom traits that you create for your app. These traits can then be imported and used in your templates to add functionality to your UI components.

- **types**:
Type definitions for the app. This can include types for the state, actions, and any other relevant data structures.

- **ui**:
Using proper idiomatic OEM usually allows for their to be a single UI as one large template function that renders the entire app since state in OEM is made up of a number of reactive state objects that can be used anywhere and not tied to any single template or component. However, in more complex apps, you may want to break down the UI into smaller components for better organization and readability. This file or folder can be used to store these components, which can then be imported and used in the main UI template. Components are just regular functions no different then if they written inline in the main UI template, but breaking them out can help with organization and readability.
`,
);

// Generate specs/commands/oem.md — slash command that routes to the oem subagent
const oemCommandContent = `---
description: Use OEM to generate front-end UI applications and components
allowed-tools: Task
argument-hint: <your UI request>
---

Use the \`oem\` subagent to handle this request:

$ARGUMENTS
`;

await Bun.write(`${specDir}/commands/oem.md`, oemCommandContent);
await Bun.write(`${resolve(projectRoot, '.claude')}/commands/oem.md`, oemCommandContent);

// Generate www/llms.txt — a single file with all documentation for LLM consumption
await Bun.write(
  `${wwwDir}/llms.txt`,
  `# OEM

> OEM is an agent-first UI framework and toolkit engineered for human-AI collaboration. It provides a design-token-driven system for generating declarative, reactive UI via a compositional syntax that unifies markup, styling, and behavior.

## Core Library

${coreFiles.map(([, , content]: any) => stripFrontMatter(content)).join('\n\n---\n\n')}

## Trait Library

${traitFiles.map(([, , content]: any) => stripFrontMatter(content)).join('\n\n---\n\n')}

## State Library

${stateFiles.map(([, , content]: any) => stripFrontMatter(content)).join('\n\n---\n\n')}

## Theme Library

${themeFiles.map(([, , content]: any) => stripFrontMatter(content)).join('\n\n---\n\n')}
`,
);
