#!/usr/bin/env bun

import { Glob } from 'bun';
import { resolve } from 'node:path';
import { extractFrontMatter } from 'scripts/helpers';

const projectRoot = resolve(import.meta.dir, '..');
const specDir = resolve(projectRoot, 'specs');

// delete the specs directory if it exists, then recreate it with the necessary subdirectories
if (await Bun.file(specDir).exists()) {
  await Bun.file(specDir).unlink();
}

// copy core files to specs/references/core
const coreFiles = ['template.md', 'state.md', 'types.md'];
for (const fileName of coreFiles) {
  const source = resolve(projectRoot, `src/core/${fileName}`);
  const dest = resolve(specDir, `./references/core/${fileName}`);
  await Bun.write(dest, await Bun.file(source).text());
}

const traitFiles = [];
for await (const file of new Glob('src/traits/*.md').scan('.')) {
  const filePath = resolve(projectRoot, file);
  const content = await Bun.file(file).text();
  const fileName = file.split('/').pop()!;
  const frontMatter = extractFrontMatter(await Bun.file(filePath).text());
  // copy to references/traits
  const referencePath = `${specDir}/references/traits/${fileName}`;
  await Bun.write(referencePath, content);
  traitFiles.push([`./references/traits/${fileName}`, frontMatter]);
}

const stateFiles = [];
for await (const file of new Glob('src/states/*.md').scan('.')) {
  const filePath = resolve(projectRoot, file);
  const content = await Bun.file(file).text();
  const fileName = file.split('/').pop()!;
  const frontMatter = extractFrontMatter(await Bun.file(filePath).text());
  // copy to references/states
  const referencePath = `${specDir}/references/states/${fileName}`;
  await Bun.write(referencePath, content);
  stateFiles.push([`./references/states/${fileName}`, frontMatter]);
}

const themeFiles = [];
for await (const file of new Glob('src/themes/tokens/*.md').scan('.')) {
  const filePath = resolve(projectRoot, file);
  const content = await Bun.file(file).text();
  const fileName = file.split('/').pop()!;
  const frontMatter = extractFrontMatter(await Bun.file(filePath).text());
  // copy to references/tokens
  const referencePath = `${specDir}/references/tokens/${fileName}`;
  await Bun.write(referencePath, content);
  themeFiles.push([`./references/tokens/${fileName}`, frontMatter]);
}

const moduleFiles = [];
for await (const file of new Glob('src/modules/*.md').scan('.')) {
  const filePath = resolve(projectRoot, file);
  const content = await Bun.file(file).text();
  const fileName = file.split('/').pop()!;
  const frontMatter = extractFrontMatter(await Bun.file(filePath).text());
  // copy to references/modules
  const referencePath = `${specDir}/references/modules/${fileName}`;
  await Bun.write(referencePath, content);
  moduleFiles.push([`./references/modules/${fileName}`, frontMatter]);
}

// Create an empty Skill.md (overwrite if exists)
await Bun.write(
  `${specDir}/agents/oem.md`,
  `---
name: oem
description: Manual for generating front-end applications using OEM, the agent-first UI framework and toolkit.
---

# This Guide

You are a front-end expert and an expert at writing idiomatic OEM. This document is a guide and canonical reference on how OEM applications are structured and how to use the framework effectively and write OEM's distinctive compositional syntax that declaratively unifies markup, styling, and behavior.

## Core Library & Fundamentals

The core library provides the fundamental building blocks of the OEM ecosystem. It includes the Template function for creating a user-defined templating engine, the State function for creating a micro event-bus and state object, and the ThemeState function for managing design tokens in a centralized way. The core library also includes type definitions for OEM, which can be found in the references.

${coreFiles
  .map((fileName) => `- [${fileName.replace('.md', '')}](${`./references/core/${fileName}`})`)
  .join('\n')}


## Trait Library

The following traits come with OEM. Traits are reusable pieces of logic that give the abilities and behaviors to your custom template engine. They can be thought of as plugins that can be applied to the output of the Template function to create a powerful and flexible system for generating UI.

${traitFiles
  .map(
    ([filePath, frontMatter]: any) =>
      `- [${frontMatter.name}](${filePath}) - ${frontMatter.description}`,
  )
  .join('\n')}


## State Library

OEM's state management system is simple yet powerful, providing a flexible way to manage state in your applications. The following states are available in the OEM ecosystem:

${stateFiles
  .map(
    ([filePath, frontMatter]: any) =>
      `- [${frontMatter.name}](${filePath}) - ${frontMatter.description}`,
  )
  .join('\n')}

## Theme Library

OEM doesn't have components or other predefined UI elements. Instead, all elements, component, features, etc. are generated by LLMs interpreting design tokens which follows a naming convention that prescribes both structure and usage. This allows for a much more flexible and adaptable system that can be used to generate any kind of UI. 

### Naming:
Primitives > Semantics > Expressions

### Composition:
Elements > Components > Features

### Tokens:
${themeFiles
  .map(
    ([filePath, frontMatter]: any) =>
      `- [${frontMatter.name}](${filePath}) - ${frontMatter.description}`,
  )
  .join('\n')}

Note: The "theme" Module in the Module Library is a ready-to-go singleton instance of the ThemeState object which can be used off the shelf for managing design tokens in your application.

## Module Library

Modules are globally available singleton instances of objects to be used off the shelf. Currently, the only module available in the OEM ecosystem is the "theme" module which is a singleton instance of the ThemeState object. This allows you to manage your design tokens in a centralized way and easily access them throughout your application.

${moduleFiles
  .map(
    ([filePath, frontMatter]: any) =>
      `- [${frontMatter.name}](${filePath}) - ${frontMatter.description}`,
  )
  .join('\n')}

## Pattern Library

### Idiomatic OEM

- Don't use ternary operators. Instead, use traits to conditionally apply styles and behaviors. This keeps the declarative syntax consistent and allows for better LLM interpretation and management.

### Git Commits

### Architectural Patterns

OEM is designed to be flexible and adaptable to a wide range of architectural patterns. However, there are a few patterns that are particularly well-suited to the OEM ecosystem:

#### SPA

SPAs have a prescribed structure in order to keep a clean separation of concerns

File structure should be based on High Cohesion and Low Coupling and optimized for LLM interpretation and management. Based on complexity, the following items could exist either as single files or folders with files.

- **actions**:
A library of all the actions that can be dispatched in the app. Each action is a function that returns an object with a type and a payload.

- **machines**:
State machines that define the behavior of the app. Each machine has a state, a set of transitions, and a set of actions that can be dispatched. Implement them as simple switch statements, switching on the current state and the dispatched action.

- **main**:
The entry point of the app. It initializes the state machine and sets up the event listeners for the UI. It also renders the UI based on the current state of the machine.

- **templates**:
A library of templates (using Template and it's destructured [tag, trait]) that can be used to render the UI.

- **traits**:
Any custom traits that are needed for the app that aren't already provided by the core library or that could dramatically simplify the implementation. For example, a trait for handling form input or a trait for managing a list of items.

- **types**:
Type definitions for the app. This can include types for the state, actions, and any other relevant data structures.

- **ui**:
Functions for rendering the UI based on the current state of the machine. This can include functions for rendering different components of the UI, such as a list of todo items or a form for adding new items.

- **theme**:
A set of semantic tokens for styling the app. This can include colors, fonts, spacing, and any other design elements that are used throughout the app.
`,
);
