/**
 * Design Token System — 6-Layer Architecture
 *
 * OEM has NO component library. All UI is generated by LLMs interpreting
 * design tokens. Tokens prescribe both structure and usage through a strict
 * naming convention so that code-generation agents can produce consistent,
 * theme-aware interfaces without pre-built components.
 *
 * ─── TOKEN SELECTION CASCADE (for generated UI code) ───
 *
 * When styling UI, search for the most specific token first:
 *
 *   1. ftr_  (feature)   → product-specific overrides (checkout, dashboard …)
 *   2. cmp_  (component) → fully-styled component variants (buttons, cards …)
 *   3. elm_  (element)   → atomic element base properties (sizes, radii …)
 *   4. sem_  (semantic)  → purpose-based fallback (colors, spacing, typography)
 *   5. inline style      → absolute last resort for truly unique one-off values
 *
 * ─── BANNED IN UI CODE ───
 *
 *   • pmt_ (primitives)  → NEVER use directly in trait.style() or UI code.
 *   • exp_ (expression)  → NEVER use directly in trait.style() or UI code.
 *
 *   These layers exist only to define theme values. They feed into the
 *   semantic layer and must never leak into generated output.
 *
 * ─── ARCHITECTURE LAYERS (strict dependency order) ───
 *
 *   1. pmt (primitives)  → raw measurable values
 *   2. exp (expression)  → global personality controls
 *   3. sem (semantic)    → UI meaning assignment
 *   4. elm (element)     → atomic UI parts
 *   5. cmp (component)   → design system components
 *   6. ftr (feature)     → product-level overrides
 *
 * Naming Rules:
 * - Flat structure only (no nesting)
 * - snake_case naming
 * - Minimum 3-letter abbreviations (except _x, _y, _sm, _md, _lg)
 * - Values: string | number
 * - References: {token_name} syntax
 * - Tokens may only reference lower layers
 *
 * Abbreviation Key:
 * - pmt=primitives, exp=expression, sem=semantic, elm=element, cmp=component, ftr=feature
 * - bkg=background, btn=button, txt=text, bdr=border, pad=padding, spc=spacing
 * - fnt=font, siz=size, wgt=weight, hgt=height, wdt=width, rad=radius
 * - hov=hover, act=active, dis=disabled, foc=focus, pri=primary, sec=secondary
 */

export * from './component';
export * from './element';
export * from './expression';
export * from './feature';
export * from './primitives';
export * from './semantic';

import type { ComponentTokens } from './component';
import type { ElementTokens } from './element';
import type { ExpressionTokens } from './expression';
import type { FeatureTokens } from './feature';
import type { PrimitiveTokens } from './primitives';
import type { SemanticTokens } from './semantic';

/**
 * Base tokens — internal / theme-definition only.
 * These layers (primitives, expression, semantic) define the raw values and
 * meaning mappings that power the design system. They must NEVER be referenced
 * directly in UI code or trait.style() calls.
 */
export type BaseTokens = PrimitiveTokens & ExpressionTokens & SemanticTokens;

/**
 * UI tokens — the layers that generated UI code should reference.
 * Use these (element, component, feature) in trait.style() calls and template
 * styling. When no elm_/cmp_/ftr_ token fits, fall back to sem_ tokens from
 * BaseTokens, then inline styles as a last resort.
 */
export type UITokens = ElementTokens & ComponentTokens & FeatureTokens;

/**
 * Complete design token system combining all 6 layers.
 */
export type DesignTokens = BaseTokens & UITokens;
