/**
 * Design Token System — 2-Layer Architecture
 *
 * OEM has NO component library. All UI is generated by LLMs interpreting
 * design tokens. Tokens prescribe both structure and usage through a strict
 * naming convention so that code-generation agents can produce consistent,
 * theme-aware interfaces without pre-built components.
 *
 * ─── TOKEN SELECTION CASCADE (for generated UI code) ───
 *
 * When styling UI, search for the most specific token first:
 *
 *   1. cmp_  (component) → all UI parts: structural properties (sizes,
 *                           spacing, radii) AND visual/state properties
 *                           (colors, shadows, transitions, variants)
 *   2. sem_  (semantic)  → purpose-based fallback (colors, spacing, typography)
 *   3. inline style      → absolute last resort for truly unique one-off values
 *
 * ─── ARCHITECTURE LAYERS ───
 *
 *   1. sem (semantic)    → UI meaning assignment — colors, spacing, typography,
 *                          radius, shadows, motion, effects
 *   2. cmp (component)   → all UI parts, from atomic controls to complex widgets
 *
 * Naming Rules:
 * - Flat structure only (no nesting)
 * - snake_case naming
 * - Minimum 3-letter abbreviations (except _x, _y, _sm, _md, _lg)
 * - Values: string | number
 * - References: {token_name} syntax
 * - cmp_ tokens may reference sem_ tokens
 *
 * Abbreviation Key:
 * - sem=semantic, cmp=component
 * - bkg=background, btn=button, txt=text, bdr=border, pad=padding, spc=spacing
 * - fnt=font, siz=size, wgt=weight, hgt=height, wdt=width, rad=radius
 * - hov=hover, act=active, dis=disabled, foc=focus, pri=primary, sec=secondary
 */

export * from './component';
export * from './semantic';

import type { ComponentTokens } from './component';
import type { SemanticTokens } from './semantic';

/**
 * Complete design token system combining both layers.
 */
export type DesignTokens = SemanticTokens & ComponentTokens;
