declare namespace OEM {
  export interface Number {
    get: () => number;
    set(n: number): OEM.Number;
    inc: (n: number) => OEM.Number;
    dec: (n: number) => OEM.Number;
    val: number;
    sub: (cb: (n: number) => any) => void;
  }
  export interface Element {
    column(gap: number, align?: 'start' | 'center' | 'end', justify?: 'start' | 'center' | 'end'): OEM.Element;
    innerHtml(...nodes: Node[]): HTMLElement;
    innerText(...txt: (string | number | OEM.Number['get'])[]): HTMLElement;
    onClick<F extends (...args: any[]) => any>(func: F, ...args: Parameters<F>): OEM.Element;
    row(gap: number, align?: 'start' | 'center' | 'end', justify?: 'start' | 'center' | 'end'): OEM.Element;
  }
}

// Declare Number
declare const NUMBER: OEM.Number;

// Declare Elements
declare const A: OEM.Element;
declare const ABBRADDRESS: OEM.Element;
declare const AREA: OEM.Element;
declare const ARTICLE: OEM.Element;
declare const ASIDE: OEM.Element;
declare const AUDIO: OEM.Element;
declare const B: OEM.Element;
declare const BASE: OEM.Element;
declare const BDI: OEM.Element;
declare const BDO: OEM.Element;
declare const BLOCKQUOTE: OEM.Element;
declare const BODY: OEM.Element;
declare const BR: OEM.Element;
declare const BUTTON: OEM.Element;
declare const CANVAS: OEM.Element;
declare const CAPTION: OEM.Element;
declare const CITE: OEM.Element;
declare const CODE: OEM.Element;
declare const COL: OEM.Element;
declare const COLGROUP: OEM.Element;
declare const DATA: OEM.Element;
declare const DATALIST: OEM.Element;
declare const DD: OEM.Element;
declare const DEL: OEM.Element;
declare const DETAILS: OEM.Element;
declare const DFN: OEM.Element;
declare const DIALOG: OEM.Element;
declare const DIV: OEM.Element;
declare const DL: OEM.Element;
declare const DT: OEM.Element;
declare const EM: OEM.Element;
declare const EMBED: OEM.Element;
declare const FIELDSET: OEM.Element;
declare const FIGCAPTION: OEM.Element;
declare const FIGURE: OEM.Element;
declare const FOOTER: OEM.Element;
declare const FORM: OEM.Element;
declare const H1: OEM.Element;
declare const H2: OEM.Element;
declare const H3: OEM.Element;
declare const H4: OEM.Element;
declare const H5: OEM.Element;
declare const H6: OEM.Element;
declare const HEAD: OEM.Element;
declare const HEADER: OEM.Element;
declare const HGROUP: OEM.Element;
declare const HR: OEM.Element;
declare const HTML: OEM.Element;
declare const I: OEM.Element;
declare const IFRAME: OEM.Element;
declare const IMG: OEM.Element;
declare const INPUT: OEM.Element;
declare const INS: OEM.Element;
declare const KBD: OEM.Element;
declare const LABEL: OEM.Element;
declare const LEGEND: OEM.Element;
declare const LI: OEM.Element;
declare const LINK: OEM.Element;
declare const MAIN: OEM.Element;
declare const MAP: OEM.Element;
declare const MARK: OEM.Element;
declare const MENU: OEM.Element;
declare const META: OEM.Element;
declare const METER: OEM.Element;
declare const NAV: OEM.Element;
declare const NOSCRIPT: OEM.Element;
declare const OBJECT: OEM.Element;
declare const OL: OEM.Element;
declare const OPTGROUP: OEM.Element;
declare const OPTION: OEM.Element;
declare const OUTPUT: OEM.Element;
declare const P: OEM.Element;
declare const PICTURE: OEM.Element;
declare const PRE: OEM.Element;
declare const PROGRESS: OEM.Element;
declare const Q: OEM.Element;
declare const RP: OEM.Element;
declare const RT: OEM.Element;
declare const RUBY: OEM.Element;
declare const S: OEM.Element;
declare const SAMP: OEM.Element;
declare const SCRIPT: OEM.Element;
declare const SECTION: OEM.Element;
declare const SELECT: OEM.Element;
declare const SLOT: OEM.Element;
declare const SMALL: OEM.Element;
declare const SOURCE: OEM.Element;
declare const SPAN: OEM.Element;
declare const STRONG: OEM.Element;
declare const STYLE: OEM.Element;
declare const SUB: OEM.Element;
declare const SUMMARY: OEM.Element;
declare const SUP: OEM.Element;
declare const TABLE: OEM.Element;
declare const TBODY: OEM.Element;
declare const TD: OEM.Element;
declare const TEMPLATE: OEM.Element;
declare const TEXTAREA: OEM.Element;
declare const TFOOT: OEM.Element;
declare const TH: OEM.Element;
declare const THEAD: OEM.Element;
declare const TIME: OEM.Element;
declare const TITLE: OEM.Element;
declare const TR: OEM.Element;
declare const TRACK: OEM.Element;
declare const U: OEM.Element;
declare const UL: OEM.Element;
declare const VAR: OEM.Element;
declare const VIDEO: OEM.Element;
declare const WBR: OEM.Element;
